mail:
  domain: gmail.com
logging:
  level:
    org:
      springframework:
        security: ERROR
    com:
      demo: DEBUG
      netflix:
        zuul: DEBUG
endpoints:
  actuator:
    enabled: true
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
management:
  security:
    enabled: false
  
