server:
  port: 8899
  contextPath: /userauth
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  user:
    password: password

spring:
  cloud:
    consul:
      discovery:
        enabled: true
        register-health-check: true
        register: true
        fail-fast: false
        health-check-path: ${server.contextPath}/health
      config:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
    username: root
    driver-class: com.mysql.jdbc.Driver
  data:
    mongodb:
    host: localhost
    port: 27017
    database: auth-server
 # jpa:
 #   database-platform: org.hibernate.dialect.MySQLDialect
 #   show-sql: false
 #   hibernate:
 #     ddl-auto: create
