server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
  hostname: localhost
  port: 8899
  contextPath: userauth

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
spring:
  cloud:
    consul:
      discovery:
        enabled: true
        register-health-check: true
        register: true
        fail-fast: false
        health-check-path: /health
      config:
        enabled: true
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
    client:
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      userAuthorizationUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/authorize
      clientId: acme
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasks