server:
  port: 8090
  contextPath: /web
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    consul:
      discovery:
        enabled: true
        register-health-check: true
        register: true
        fail-fast: false
        health-check-path: ${server.contextPath}/health
      config:
        enabled: true